### ISSUE TITLE
Union UnreachableFix and ExhaustiveUnionFix types are unused

### ISSUE THREAD

**Issue by gyrfalcon** [LoganBarnett/flow-degen#2]
When using degenSum (I think this is the culprit) two types are added to the generated file <UnionType>UnreachableFix / <UnionType>ExhaustiveUnionFix. These types are referenced in comments, but not in the code. On projects that use a linter to ensure there are no unused declarations, these types will cause an error.

I'm assuming the bug is really that these types /should/ be used somewhere but aren't.

**Comment by LoganBarnett** [comment]
These types have risen from the dead! Fixed in v0.8.0.
